### ISSUE TITLE
Hard Coded GOPATH In bashrc File

### ISSUE THREAD

**Issue by amayer5125** [jasonodonnell/CoreDNS-Ansible#1]
There is a hard coded GOPATH in the bashrc file of the common role. Should this be removed since it is also set in the env10.sh file?

**Comment by jasonodonnell** [comment]
Fixed here: https://github.com/jasonodonnell/CoreDNS-Ansible/commit/c913804af2e8192f53ae8e4db961bc28ecb4dcac

Thanks @amayer5125 !
